### ISSUE TITLE
how to inferece use your model on my own video or image?

### ISSUE THREAD

**Issue by flyduck** [CSAILVision/GazeCapture#10]
hi,
firstly, thanks your grate work!
but when I use your pytorch model I have some question:
(1)which is pre-trained model to is useable?
(2)if I want to inference on my own image or video, how it can be work?

thanks very much!

**Comment by erkil1452** [comment]
(1) I recommend to use the pytorch model which there is only one.
(2) Modify the ITrackerData.py to load your own images.

**Comment by btilmon** [comment]
Could you please elaborate on this? I am trying to load my own image and getting large errors.

**Comment by ceyxasm** [comment]
@btilmon did you have any success?
