### ISSUE TITLE
Run time Error in Reading Kernel Image

### ISSUE THREAD

**Issue by Madankumar90** [CSAILVision/GazeCapture#15]
After Getting the metadata i am running it with main.py but when i do initially i get the warning "Found GPU0 Quadro K1100M which is of cuda capability 3.0. PyTorch no longer supports this GPU because it is too old.     The minimum cuda capability that we support is 3.5." and then i get the run time error "CUDA Cannot read kernel image". I am not able to relate this problem??. I am running through anaconda Windows 10, CUDA 9.0 and pytorch 0.4.1. Thank you.

**Comment by erkil1452** [comment]
Hi, we currently use pytorch 1.0 so you may need to upgrade it to run the code. The older version of the code was actually running under 0.4.1 so you may also try that.

**Comment by Madankumar90** [comment]
Thanks for the reply. where can i find the older version of the code that runs with the version 0.4.1?

**Comment by erkil1452** [comment]
In the github history.
