### ISSUE TITLE
Size of FaceGrid's Content

### ISSUE THREAD

**Issue by Vampire-Vx** [CSAILVision/GazeCapture#16]
Given that the input image is a rectangle and input face is square, and face grid is calculated from these two images. However,  when I view the facegrid data, I find that the height and width are the same, for example 14 x 14. How to generate face grid with square shape content?

**Comment by erkil1452** [comment]
We enlarge the detected faces to have a square shape. Therefore the are of the face will always be square even if the entire frame is a rectangle. This is why the grid region may or may not be a square depending on the rounding when computing the projection to the 25x25 grid.

**Comment by erkil1452** [comment]
Additionally, the grid shape can also be cut by border culling if the face is close to the image border.
