### ISSUE TITLE
Project Website Down

### ISSUE THREAD

**Issue by btilmon** [CSAILVision/GazeCapture#18]
Can anyone access the website?

**Comment by erkil1452** [comment]
Hm, I guess we should really change hosting.

**Comment by btilmon** [comment]
Is there any way you could send me a link to the data? I registered with btilmon@ufl.edu.

Thanks,
Brevin

**Comment by caxelos** [comment]
same problem here

**Comment by erkil1452** [comment]
The website has been moved to a new server. You may need to register again because of the old database backup used to recover the state.
