### ISSUE TITLE
I/O Error(Errno 5) when running prepareDataset.py

### ISSUE THREAD

**Issue by caxelos** [CSAILVision/GazeCapture#21]
* **Solution**: Check down my last comment.It was caused by a fault in my **hardware**.

* I am facing an I/O error "OSError: [Errno 5] Input/output error" when running 
**prepareDataset.py**

* I found in internet that I can redirect the output using ``` >/dev/null 2>&1``` after
the command,but it doesnt create all subdirectories
```
python prepareDataset.py --dataset_path [A = where extracted] --output_path [B = where to save new data]
```

* Is this command running fine at your system? I am using **Ubuntu 16.04 LTS**

* I write below the error backtrace:
Traceback (most recent call last):
  File "prepareDataset.py", line 273, in <module>
    main()
  File "prepareDataset.py", **line 125**, in main
    img = np.array(img.convert('RGB'))
  File "/home/user/anaconda3/envs/myenv/lib/python3.6/site-packages/PIL/Image.py", line 934, in convert
    self.load()
  File "/home/user/anaconda3/envs/myenv/lib/python3.6/site-packages/PIL/ImageFile.py", line 234, in load
    s = read(self.decodermaxblock)
  File "/home/user/anaconda3/envs/myenv/lib/python3.6/site-packages/PIL/JpegImagePlugin.py", line 398, in load_read
    s = self.fp.read(read_bytes)

**Comment by erkil1452** [comment]
Hi, try debugging the code in the Python debugger. Perhaps your paths are wrong and the files are not existing.

**Comment by erkil1452** [comment]
Try checking os.file.isfile(...) before calling the Image.load().

**Comment by caxelos** [comment]
@erkil1452 Thanks for the quick response.
* I checked the paths.The problem was not in the paths,it was in some images,which seemed to be **corrupted** because I couldn't open them with an image viewer(very few images).
* It may be my fault the reason why they are corrupted(problematic copy in disk perhaps) 
* I solved it by adding an IOError exception and I **omit** these images,because they are very few.

```
for j,frame in enumerate(frames):
       try: 
               ...rest of code...
               img = Image.open(imgFile)
               ...rest of code...
       except IOError:
              pass
 

```

**Comment by erkil1452** [comment]
Ok, I am happy you have found a solution.

**Comment by caxelos** [comment]
* I have found the solution in order **not** to skip these images.
* It was my fault,my external **hard drive** where I saved the database had **hardware errors**
and was not working properly.I replaced it with a **new** 1TB external drive and everything worked fine without any error.
* I **apologize** for the confusion,however that problem occured during the **preprocess** procedure and I couldn't imagine that my external drive had been **damaged**
