### ISSUE TITLE
Anyone had luck with pytorch inference?

### ISSUE THREAD

**Issue by btilmon** [CSAILVision/GazeCapture#22]
Has anyone achieved accurate predictions using their own data with the pytorch implementation? I am getting inaccurate predictions after just changing the data loading paths in ITrackerData.py and using the checkpoint.

**Comment by erkil1452** [comment]
Are these with the original dataset or using your own images?

**Comment by btilmon** [comment]
Thanks for responding. I am using the checkpoint trained on your dataset, but am testing with images from a iPhone 6s plus camera. Have you seen people have good results testing with their own data? I get much better results in pytorch than caffe when testing with my own data. 

When looking directly into camera, pytorch gaze estimate = [42,75], caffe gaze estimate = [-195,-195]. I am normalizing before I subtract.

**Comment by erkil1452** [comment]
The prediction should be in cm so both of these numbers are widely wrong. I would maybe try to take an image from the dataset similar to yours and try to compare them, maybe blend them or generally see what is the difference in the intermediate values. The pytorch code lets you easily dump intermediate outputs. The numbers have to be order of magnitude different. I do not use caffe anymore.

**Comment by btilmon** [comment]
Thanks for the input.

**Comment by btilmon** [comment]
I have fixed this issue, getting an average predicted gaze of [.8, 1.2] over 10 images when looking directly into iphone camera using the checkpoint in pytorch. I was making my face grid wrong. Thanks for your help!

**Comment by erkil1452** [comment]
Good to hear that. That sound about right.
