### ISSUE TITLE
About train and test augmentation mentioned in the paper

### ISSUE THREAD

**Issue by bclyc** [CSAILVision/GazeCapture#24]
Hello, could you pls share the parameters of train/test augmentation that are mentioned in the Itracker paper? 
The only description in the paper was 'shifting the eyes and the face, changing face grid appropriately.' Could u pls tell us the values/ranges? We just can't reproduce ur accuracy with test augmentions...
Thanks!

**Comment by erkil1452** [comment]
The augmentation was (AFAIK) only used for the training and it basically simulated shifting the face detection up/down/left/right by a spatial distance corresponding to a size of cell in the face grid (i.e., how many pixels each cell covers in the input image).

**Comment by bclyc** [comment]
Thank you for the response! Could you pls share the range of shifting (i.e. how many cells in the facegrid)?
Here's another issue: using [resize->224 then sub mean image] on cropped patches, we get the right performance on your 1x model (2.04 on iphone testset in the paper), but worse accuracy on your 25x model (2.22 on iphone testset which should be 1.86 in the paper). Why? Is it because you used different data process before feed into network? 
Thanks lot for ur help!

**Comment by btilmon** [comment]
Did you shift the ground truth gaze relative to the augment shift?

**Comment by erkil1452** [comment]
There are 25 augmentations which is a shift by cell count in {[-2; 2] x [-2; 2]} (up to to in each direction). The cell size is image size / grid resolution that is round(224 / 25) = 9 px. 

I do not think we augment the gaze. The paper says that in the test phase we also augment the test dataset and then average the predictions. However, this is not necessary to get a single prediction.
