### ISSUE TITLE
Link to paper is incorrect

### ISSUE THREAD

**Issue by joncamp** [CSAILVision/GazeCapture#25]
The link to the paper on https://gazecapture.csail.mit.edu/index.php is not working. 

Current Link: https://gazecapture.csail.mit.edu/cvpr2016_gazecapture.pdf
Result: 404

Working Link: https://people.csail.mit.edu/khosla/papers/cvpr2016_Khosla.pdf

**Comment by erkil1452** [comment]
Thank you. It has been fixed.
