### ISSUE TITLE
Explore page not working on https://gazecapture.csail.mit.edu/explore.php

### ISSUE THREAD

**Issue by joncamp** [CSAILVision/GazeCapture#26]
Navigate to https://gazecapture.csail.mit.edu/explore.php. On that page, there is only a black image. There are some errors in the console, and debugging the JavaScript at a high level (since the code is minified) shows that it calling code in https://gazecapture.csail.mit.edu/js/load-image.all.min.js.

HTML1521: Unexpected "</body>" or end of file. All open elements should be closed before the end of the document.

**Comment by erkil1452** [comment]
Hi, thank you for your report but the website is hosted at MIT and I no longer have access to the files to fix it.
