### ISSUE TITLE
pytorch checkpoint is corrupted

### ISSUE THREAD

**Issue by parthjshah95** [CSAILVision/GazeCapture#27]
The tarfile seems to be corrupted: `pytorch/checkpoint.pth.tar`

**Comment by erkil1452** [comment]
Do you use the correct version of pytorch (0.4.1) ?

**Comment by parthjshah95** [comment]
Yes, but the _tar_ file seems to be corrupted; I cannot extract the pytorch checkpoint. Torch will only be able to read the extracted file, right?

**Comment by parthjshah95** [comment]
I wrongly assumed it was a tar file because of the extension. Was able to load it with torch directly.
