### ISSUE TITLE
is it likely to run with latest pytorch on ngc cloud pytorch docker container?

### ISSUE THREAD

**Issue by AndreV84** [CSAILVision/GazeCapture#28]
Steps to reproduce the issue:

-  start a cloud instance with GPU, at Google Cloud Platform: https://console.cloud.google.com/marketplace/details/nvidia-ngc-public/nvidia-gpu-cloud-pytorch-image?q=pytorch&id=9b7fee75-4130-40c6-b055-c56a4f49d42a
clone the repo:
`git clone https://github.com/CSAILVision/GazeCapture/
cd GazeCapture
`
-  pull a docker container:
`docker pull nvcr.io/nvidia/pytorch:20.02-py3
`
download the dataset:
```
mkdir database && cd database
wget -O gazecapture.tar "https://gazecapture.csail.mit.edu/dataset.php?
```
`tar -xvf  gazecapture.tar`
`cat *.tar.gz | tar zxvf - -i`

- start the container  
`docker run --gpus all -it --rm -v /home/user/GazeCapture:/mount nvcr.io/nvidia/pytorch:20.02-py3
`
enter the folder and execute the following steps
`cd  /mount`
`python prepareDataset.py --dataset_path base/--output_path output
`
`python main.py --data_path output --reset`

**Comment by AndreV84** [comment]
python main.py --data_path /mount/output --reset
Loading iTracker dataset...
        Reading metadata from /mount/output/metadata.mat...
        Reading metadata from ./mean_face_224.mat...
        Reading metadata from ./mean_left_224.mat...
        Reading metadata from ./mean_right_224.mat...
Loaded iTracker dataset split "train" with 1251983 records...
Loading iTracker dataset...
        Reading metadata from /mount/output/metadata.mat...
        Reading metadata from ./mean_face_224.mat...
        Reading metadata from ./mean_left_224.mat...
        Reading metadata from ./mean_right_224.mat...
Loaded iTracker dataset split "test" with 179496 records...
ERROR: Unexpected bus error encountered in worker. This might be caused by insufficient shared memory (shm).
ERROR: Unexpected bus error encountered in worker. This might be caused by insufficient shared memory (shm).
ERROR: Unexpected bus error encountered in worker. This might be caused by insufficient shared memory (shm).
ERROR: Unexpected bus error encountered in worker. This might be caused by insufficient shared memory (shm).
ERROR: Unexpected bus error encountered in worker. This might be caused by insufficient shared memory (shm).
ERROR: Unexpected bus error encountered in worker. This might be caused by insufficient shared memory (shm).
Traceback (most recent call last):
  File "/opt/conda/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 761, in _try_get_data
    data = self._data_queue.get(timeout=timeout)
  File "/opt/conda/lib/python3.6/queue.py", line 173, in get
    self.not_empty.wait(remaining)
  File "/opt/conda/lib/python3.6/threading.py", line 299, in wait
    gotit = waiter.acquire(True, timeout)
  File "/opt/conda/lib/python3.6/site-packages/torch/utils/data/_utils/signal_handling.py", line 66, in handler
    _error_if_any_worker_fails()
RuntimeError: DataLoader worker (pid 412) is killed by signal: Bus error. It is possible that dataloader's workers are out of shared memory. Please try to raise your shared memory limit.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "main.py", line 302, in <module>
    main()
  File "main.py", line 132, in main
    train(train_loader, model, criterion, optimizer, epoch)
  File "main.py", line 158, in train
    for i, (row, imFace, imEyeL, imEyeR, faceGrid, gaze) in enumerate(train_loader):
  File "/opt/conda/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 345, in __next__
    data = self._next_data()
  File "/opt/conda/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 841, in _next_data
    idx, data = self._get_data()
  File "/opt/conda/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 798, in _get_data
    success, data = self._try_get_data()
  File "/opt/conda/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 774, in _try_get_data
    raise RuntimeError('DataLoader worker (pid(s) {}) exited unexpectedly'.format(pids_str))
RuntimeError: DataLoader worker (pid(s) 412) exited unexpectedly
terminate called without an active exception
Aborted (core dumped)

**Comment by AndreV84** [comment]
--shm-size 8G
seems to be the solution

**Comment by AndreV84** [comment]
docker run --gpus all --shm-size 32G -it --rm -v /home/nvidia/GazeCapture:/mount nvcr.io/nvidia/pytorch:20.02-py3

**Comment by AndreV84** [comment]
when I run the test step it proceeds and finishes with "DONE"
How do I find results? How do I put new images to run the model on them? How do I locate coordinates of gaze from new pictures?
Any guidelines?
Thanks

**Comment by erkil1452** [comment]
The results are available in "output" in main.py: line 175 as a Nx[x,y] torch tensor.
If you want to provide your own inputs, modify ITrackerData.py and provide your own face image, eye crops and the face grid.

**Comment by AndreV84** [comment]
Than you for following up!
