### ISSUE TITLE
Eye Bounding Box

### ISSUE THREAD

**Issue by bocsiboti** [CSAILVision/GazeCapture#3]
Hi,
As far as I know the iOS face/eye detection service does not provide bounding boxes for eyes, only eye and eyebrow control points (landmarks). What was the procedure/algorithm that you used to generate bounding boxes for eyes from the provided information?
Thanks, Botond

**Comment by erkil1452** [comment]
It was a heuristic based on face rectangle size and eye center positions. The eye rectangle is centered around the eye center and has a size proportional to the face size.
