### ISSUE TITLE
GazeCapture dataset Download problem

### ISSUE THREAD

**Issue by huxian0402** [CSAILVision/GazeCapture#30]
Good work. But I‘m sorry that I couldn't  download GazeCapture dataset from the https://gazecapture.csail.mit.edu/download.php. Account is always unable to log in to get the correct download link due to an unknown error. I have tried many times to register and login but failed. So could you provide another available download solution. Thank you. @quantombone @adikhosla @andrewowens @visionATcsail

**Comment by jianjiandandande** [comment]
> Good work. But I‘m sorry that I couldn't download GazeCapture dataset from the https://gazecapture.csail.mit.edu/download.php. Account is always unable to log in to get the correct download link due to an unknown error. I have tried many times to register and login but failed. So could you provide another available download solution. Thank you. @quantombone @adikhosla @andrewowens @visionATcsail

me too, sent email but not reply

**Comment by huxian0402** [comment]
Now, I get the access to GazeCapture dataset. But I failed to download it because of Irregular interruption of links. @adikhosla @quantombone @zhoubolei

**Comment by xgxcheer-hit** [comment]
me too, cannot download, could anyone provide google drive or baidu drive？

**Comment by dcazzato** [comment]
Dear all, I tried to register to get access to the dataset. For the moment, I only require to know the resolution of the images composing the dataset for a report. Since I did not receive any feedback after the registration, would it be possible to obtain this information? Thank you,

**Comment by LQMSMTC** [comment]
Same here, do anyone solve this problem? Kindly remind me if you find a way to download GazeCapture dataset. I will very appreciate for your help.

**Comment by erkil1452** [comment]
I have checked the download link and it works properly for me (even over large distance). The server is administered by MIT CSAIL and it is connected by an optical fiber. I presume that the download issues are likely arising somewhere in between you and the server. Unfortunately, I cannot publish the dataset somewhere else due to the license restrictions. I suggest you to try to connect from a high-speed university cable network and use a download manager that supports resume. Another option is to first download it to a proxy server that has a better connectivity, e.g. by being located in east coast US.

**Comment by gpfworld** [comment]
me too, cannot download. Account is always unable to log in to get the correct download link due to an unknown error. I have tried many times to register and login but failed.

**Comment by nhatuan84** [comment]
> I have checked the download link and it works properly for me (even over large distance). The server is administered by MIT CSAIL and it is connected by an optical fiber. I presume that the download issues are likely arising somewhere in between you and the server. Unfortunately, I cannot publish the dataset somewhere else due to the license restrictions. I suggest you to try to connect from a high-speed university cable network and use a download manager that supports resume. Another option is to first download it to a proxy server that has a better connectivity, e.g. by being located in east coast US.

hi @erkil1452 

could you share me some pictures (10 sets) for validation?
I need it to check the available weights.

Thanks

**Comment by erkil1452** [comment]
I do not have the dataset locally. I would have to download the entire dataset first myself. Are you having problems downloading it?

**Comment by nhatuan84** [comment]
Thanks @erkil1452 

I can't register, it showed error.
If possible please help me, I just need some pics from validation dataset for testing.

**Comment by erkil1452** [comment]
Maybe I can help with the registration. What e-mail did you use to register? [You can also contact me privately if you do not want to share your e-mail here.]

**Comment by nhatuan84** [comment]
...

**Comment by constance518** [comment]
> Maybe I can help with the registration. What e-mail did you use to register? [You can also contact me privately if you do not want to share your e-mail here.]

Hi @erkil1452 can you please help me with the registration.

**Comment by erkil1452** [comment]
I am sorry I cannot find any e-mail from you. Please contact me using one of the e-mail addresses listed at https://kellnhofer.xyz and let me know the e-mail address you used for your registration at https://gazecapture.csail.mit.edu/.
