### ISSUE TITLE
Matlab Compatibility Code in prepareDataset.py

### ISSUE THREAD

**Issue by abhikr045** [CSAILVision/GazeCapture#31]
In prepareDataset.py, I encounter the following code section -
https://github.com/CSAILVision/GazeCapture/blob/e09c285eb29ab53e205175bc0bf965d9e8ce3414/pytorch/prepareDataset.py#L103

I understand that after reading the values from appleFace.json as `int`, the X & Y pixel coordinates are treated as 1-indexed values (which is Matlab compatible). So, for converting it to 0-indexed in Python, we should add **[-1,-1,0,0]** to [X,Y,W,H]. But in the code, **[-1,-1,1,1]** is added (which will increase the width & height of face crops by 1 pixel).
Can you please clarify the reason why 1 is added to W & H? I know that increment of 1 pixel wouldn't matter much, but I'd like to get clarified.
Also, for leftEyeBbox & rightEyeBbox, **[-1,-1,0,0]** should be added instead of **[0,-1,0,0]**, according to me.

Thanks.

**Comment by erkil1452** [comment]
Hi, I will not go back to the matlab code trying to find out why exactly this emerged but the entire reason is as the comment states - to reproduce the results of the matlab version. If there was a pixel added in the matlab script, this will reproduce it in sake of consistency. 1 px shift is not really a big difference so you can probably change it to your taste if you prefer. In practice you will have much larger noise coming from the face detector alone.

**Comment by abhikr045** [comment]
Okk. Thanks for the prompt response..!!
