### ISSUE TITLE
Division by 255 in SubtractMean

### ISSUE THREAD

**Issue by abhikr045** [CSAILVision/GazeCapture#32]
Hii...
Sorry to bother with a small issue - The ITrackerData.py file was revised on 26 Jan 2019, where division by 255 was introduced in **SubtractMean** class. Can you please specify the reason why this change was introduced? I mean, the code worked fine earlier without division with 255. What changed in due course of time that this change was introduced?

Thanks

**Comment by erkil1452** [comment]
Previously the division was handled by ToTensor(). It seems that pytorch behavior has changed and the mean was no longer normalized. You can put a print there and see if the mean is properly normalized. I guess it should be around 0.5 and not 127 nor 0.02.

**Comment by rahulbishain** [comment]
Thanks for the quick help Petr. Apparently, between pytorch [1.0.0](https://pytorch.org/docs/1.0.0/torchvision/transforms.html?highlight=totensor#torchvision.transforms.ToTensor) and [1.0.1](https://pytorch.org/docs/1.0.1/torchvision/transforms.html?highlight=totensor#torchvision.transforms.ToTensor), ToTensor changed its behavior for np.uint8 datatype. Previously, any ndarray between 0 and 255 was normalized but later this behavior was restricted only for ndarray of type uint8

**Comment by abhikr045** [comment]
Thank you for the valuable information. That helped a lot.
