### ISSUE TITLE
Calculating faceGrid.json from appleFace.json

### ISSUE THREAD

**Issue by abhikr045** [CSAILVision/GazeCapture#33]
There were already 3 issues raised regarding faceGrid, but none of them resolved my issue, which is the following -
How is [xLo, yLo, w, h] calculated for faceGrid.json from given face bounding box [X,Y,W,H] in appleFace.json?
E.g. - For recording 00002 & frame 00000.jpg -
[frameW, frameH] = [480, 640]
scaleX = 25/480 = 0.052
scaleY = 25/640 = 0.039
face bounding box [X,Y,W,H] = [38.15, 230.04, 343.68, 343.67]

Now, according to the following code snippet -
https://github.com/CSAILVision/GazeCapture/blob/e09c285eb29ab53e205175bc0bf965d9e8ce3414/code/faceGridFromFaceRect.m#L29-L37
xLo = round(38.15 x 0.052) + 1 = 3
yLo = round(230.04 x 0.039) + 1 = 10
w = round(343.68 x 0.052) = 18
h = round(343.67 x 0.039) = 13
i.e. [xLo, yLo, w, h] = **[3, 10, 18, 13]**
but in faceGrid.json, the corresponding value given is **[6, 10, 13, 13]**.

Why is there this significant difference in faceGrid.json values? Are these values calculated by using above formulae, or some other formulae? Also, I'm beginning to suspect that the faceGrid.json might have been obtained independently & not by using some formula on appleFace.json. Please clarify..

Thanks

**Comment by erkil1452** [comment]
I did not personally generate the json files so I cannot tell you which scripts were used. From the example, it makes more sense for me to go with [3,10,18,13]. In the pytorch code ( https://github.com/CSAILVision/GazeCapture/blob/master/pytorch/prepareDataset.py ) I use the faceGrid.json and it works quite well so I think if you retrain it the exact formula may play a lesser role.

**Comment by abhikr045** [comment]
Ok, thanks.
