### ISSUE TITLE
Can use for car driver monitor and how to improve real-time performance?

### ISSUE THREAD

**Issue by l35633** [CSAILVision/GazeCapture#35]
Thank you for this great work!
I have 2 questions.
1. Can I use this for driver eye track monitor in the car?
2. Would you please provide some ideas on how to improve the real-time performance, e.g. 20 fps or so.
Thanks a lot!

**Comment by erkil1452** [comment]
Hi,

Thank you!

1. Depending on the view angle and quality of lighting it could work. We tried to get data from people with different headpose and using Amazon Turk we got naturally quite varied light conditions though the light conditions in a car are likely to be even more challenging (dark inside, bright outside). It should still be possible with manual exposure control (to prevent too dark or bright face regions) and with positioning the camera as centrally as possible (e.g. next to steering wheel).

2. In my experience the network is quite tiny and easily runs real-time on modern GPUs. 30 FPS is not a problem including some simple face detector such as dlib. What is an issue is latency but that is an engineering problem. The algorithm does not have any latency built in so it basically depends on how fast you get images from the camera through the entire pipeline. A major issue is usually the latency from camera to PC memory (for USB cameras). This is actually much easier to reduce on a closed system such as smartphones where the link between camera and memory is much faster. I believe you could easily run the network on a modern iPad using their AI acceleration. You need to re-implement it but that should be trivial compared to complexity of some advanced monitoring system.

**Comment by l35633** [comment]
Thank you for your rely so much!
