### ISSUE TITLE
How to use the caffe model and the relation about pytorch code and the trained model?

### ISSUE THREAD

**Issue by l35633** [CSAILVision/GazeCapture#36]
HI, my nice friend! I have to disturb you again.
Now I want to use the itracker_iter_92000.caffemodel directly for the inference. but I met some problems, I want to be clear more.
1. I saw the code, the training and testing code is pytorch, I wonder the caffemodel is trained by torch or by caffe code?
2. If I want to inference the image, whether I will do by the way as the pytorch code does
    (1) the image is read by RGB format, then divde 255 to 0--1 range
    (2) I think the mean image is RGB sequence to, mean image still divdes 255 to 0--1 range
    (3) Input image(left eye, right eye, face) will seperately subtract their mean image, so some values may  be below zero, we call left_eye_sub_mean_img, right_eye_sub_mean_img, face_sub_mean_img
   (4) So left_eye_sub_mean_img, right_eye_sub_mean_img, face_sub_mean_img and face_mask will be as input images to inference the two values.

I wonder what I describe is right? or maybe I miss something?
Please check for me! Thank you very much!
Best Regards

**Comment by erkil1452** [comment]
Hi,

1. The caffe code and model is the original model from the CVPR paper and it was trained and used to derive our results long before the pytorch code existed. The pytorch code is reimplementation and it does not feature the head detection augmentation described in the paper.
2. Yes, this seems right. Both the images and their means are rescaled to 0-1 by dividing their uint8 values by 255.

**Comment by l35633** [comment]
thanks a lot! Let me try.
