### ISSUE TITLE
how to draw 3D gaze direction line in the 2D image by the prediction coordinate

### ISSUE THREAD

**Issue by l35633** [CSAILVision/GazeCapture#37]
hello, dear friend!
Now I want to draw 3D gaze direction line in the 2D image by the prediction coordinate, 
would you please give me any ideas? 
Thanks a lot!

Best Regards

**Comment by erkil1452** [comment]
Hi, we did some 3D gaze rendering for our later project Gaze360: https://github.com/Erkil1452/gaze360 . You can see an example in the Colab demo here: https://colab.research.google.com/drive/1AUvmhpHklM9BNt0Mn5DjSo3JRuqKkU4y

**Comment by l35633** [comment]
thanks! man!

**Comment by l35633** [comment]
disturb again! how about the real-time performance of Gaze360, e.g. how many frames per second?
Thanks again!

**Comment by erkil1452** [comment]
We have not really used it in real time but I am sure you can modify the network to achieve real-time performance (use less frames, less layers,...).

**Comment by l35633** [comment]
ok,thanks man!
