### ISSUE TITLE
pytorch pre-trained model

### ISSUE THREAD

**Issue by AllyCasablancas** [CSAILVision/GazeCapture#39]
Hi, 
I have some questions. Is the checkpoint.pth.tar the pre-trained model used in the publish work?
It's shown that caffe pre-trained model is provided, is it possible that you can provide us the pytorch version? Is there a way to convert the caffe model to pytorch model? (we can't find a reliable tool)
Thanks >v<

**Comment by erkil1452** [comment]
Hi,
No, the caffe model is the original model used in the work. The pytorch model was trained separately, much later and does not necessarily 100% correspond to the paper. I tried to make it as close as possible but I did not do any formal tests to verify it.

About the conversion of the checkpoint. That is definitely possible but I also do not know any tool for that. You can surely try to download the original Caffe source code and modify it to load the checkpoint and export the individual weights to some text file or something. Then you can write python code to import those weights manually to a pytorch model. At the end of the day it is mostly just tensors of numbers. But it will be quite a bit of work...
