### ISSUE TITLE
Cannot download the data

### ISSUE THREAD

**Issue by mohossny** [CSAILVision/GazeCapture#4]
I registered to the website and verified my institutional email and yet cannot login to download the data. Please advise if I am missing something.

**Comment by liangwq** [comment]
+1 the same too

**Comment by WingCH** [comment]
+1 the same too

**Comment by amdgigabyte** [comment]
+1 the same too

**Comment by isazheng888** [comment]
+1 the same too

**Comment by brunoklein99** [comment]
In addition, how would one without an institutional email get the data for non profit nor commercial use?

**Comment by yulius-fxpal** [comment]
+1 I can't even get a confirmation email to verify registration.

**Comment by claytonblythe** [comment]
Does anyone have the data and could host it somewhere?

**Comment by jakob1379** [comment]
~~I got my mail verified but the access hasn't been granted yet.~~

UPDATE:
tried again and after 24 hours, approximately, I was granted access.

**Comment by pacifinapacific** [comment]
me too. I accepted email but cannot login

**Comment by wangshankun** [comment]
+1 the same too

**Comment by sainttail** [comment]
The data is always failed for me when download. The most I can download is around 13GB and failed then I need to redownload again starting from zero.

Anyone can successfully download the data? and what tool you use to download it?

PS. I use chrome to download, but I try Internet download manager and python script both also lost connection at some point and I have to redownload.

## Updated
Now it seems to actually work, because I change ISP to another company.

**Comment by erkil1452** [comment]
Thank you for your interest in our dataset. The dataset is maintained on non-commercial bases in our free time so we are limited in what we can offer.
- The dataset is only available for non-commercial purposes. We validate this using academic e-mail address of the requester.
- This limitation originates from our IRB (human experiment permission) as well as the agreement with the Amazon Turk workers featured in the dataset so it cannot be reverted.
- The server hosting the data is connected to a 10 Gb optical fiber network so the bottleneck is typically somewhere outside. We cannot easily provide alternative hosting as we need to enforce the conditions mentioned above.
