### ISSUE TITLE
Unable to Login

### ISSUE THREAD

**Issue by sengoontoh** [CSAILVision/GazeCapture#42]
I am unable to login and download the dataset. After creating an account, I tried logging in and access was denied.

**Comment by chky** [comment]
same as you

**Comment by sengoontoh** [comment]
Will someone fix it?

**Comment by erkil1452** [comment]
Seems like a Gmail issue. It does not send the verification emails. We are working on it.

**Comment by erkil1452** [comment]
It has been temporarily patched but you need to register again if your account was not activated. That means if you have received no confirmation email after the registration, please repeat the registration.

**Comment by sengoontoh** [comment]
Hi @erkil1452 it still doesn't seem to work. I didn't receive any email.

**Comment by erkil1452** [comment]
I do not see any new registration in last 30 minutes.

**Comment by sengoontoh** [comment]
When I hit submit in the registration form, it just kicks me back to the registration form. Maybe there's something wrong in the frontend?

**Comment by erkil1452** [comment]
The form should close and the bottom of the main page should say "Thank you for registering an account! A confirmation email has just been sent to you. Please confirm your email address using the secure link in the email.". Either the validation fails (password must be 8 chars or more) or maybe your e-mail is already in db. I tried looking for you username and did not find any match.

**Comment by chky** [comment]
> The form should close and the bottom of the main page should say "Thank you for registering an account! A confirmation email has just been sent to you. Please confirm your email address using the secure link in the email.". Either the validation fails (password must be 8 chars or more) or maybe your e-mail is already in db. I tried looking for you username and did not find any match.
I have just registered and my account is chehky@mail.sim.ac.cn, I received a letter from GazeCapture team with a verification link, I click the link but it does not work

**Comment by erkil1452** [comment]
The accounts are approved manually which may take up to 1 day or more. Please try to log in later.

**Comment by chky** [comment]
> The accounts are approved manually which may take up to 1 day or more. Please try to log in later.

thanks a lot, I am able to download it now!
