### ISSUE TITLE
Laptop Gaze Inference

### ISSUE THREAD

**Issue by IndhujaRavi** [CSAILVision/GazeCapture#45]
Can I use the models for predicting gaze point on the laptop screen.

I am working on a project to track the gaze to move the mouse pointer around the screen and want to know if I can use your models to predict this gaze from a laptop's builtin webcam.

Thank you.

**Comment by erkil1452** [comment]
Maybe, depends on the webcam quality compared to our training data. At the very least you will have to calibrate some transformation function from our prediction space to your screen coordinates.

**Comment by AisanSisani** [comment]
@IndhujaRavi could you comment if made any progress, I also want to use the model in my laptop.
