### ISSUE TITLE
Unable to login and download GazeCapture dataset

### ISSUE THREAD

**Issue by shetty-shithil** [CSAILVision/GazeCapture#48]
I have registered using my institute e-mail and verified my account. But I'm unable to login and download the dataset from  https://gazecapture.csail.mit.edu/download.php.  So could you please provide another available download solution. Thank you. @quantombone @adikhosla @andrewowens @visionATcsail

**Comment by erkil1452** [comment]
Your account has been approved. Please try to log in again. Note that the approval process is manual and takes place at irregular time intervals leading to possible delays in some exceptional cases.

**Comment by shetty-shithil** [comment]
Thank you, I was granted the access and I am able to downloaded the dataset now.

**Comment by AisanSisani** [comment]
I also have the same issue, could you give me access as well.

**Comment by xuanzhao** [comment]
I also have the same issue, could you give me access as well. my account is zhaoxuan@caafc.cn

**Comment by erkil1452** [comment]
The accounts are approved manually. Please allow for several days in rare cases. It should be processed now.

**Comment by kung-bill** [comment]
Hello  I have same issue.
My email address: r08922a25@ntu.edu.tw

**Comment by erkil1452** [comment]
Yes, yes, have patience, it is a manual process. You should be fine to go now.

**Comment by rkalahasty** [comment]
Hello I also have the same issue.

My email address: 2024rkalahas@tjhsst.edu

**Comment by marycia624** [comment]
Hello, I have the same issue
265107@niuitmo.ru
@quantombone @adikhosla @andrewowens @visionATcsail

**Comment by SaniyaSebastian** [comment]
hello,I'm also having the same problem
mail id: elishatom.punnoose2021@vitstudent.ac.in

**Comment by ashintv** [comment]
facing same issue 
email -  22ct392@mgits.ac.in

**Comment by ashintv** [comment]
Its urgent 
kindly provide the access

**Comment by Tawaana19** [comment]
Hey guys, same issue here. Is there any way around this?

**Comment by Wazz37** [comment]
facing same issue. please provide access.
id - wazid.ansari@novushitech.com

**Comment by lngaxiolas** [comment]
I also have the same issue, could you give me access as well, please. My account is leopoldo.gaxiola@utculiacan.edu.mx

**Comment by malharjajoo** [comment]
I also have the same issue, could you give me access as well, please. My account email is admin@realdeed.co

**Comment by darkness650** [comment]
Hello I also have the same issue.

My email address: [2311269@mail.nankai.edu.cn](2311269@mail.nankai.edu.cn)

**Comment by feelsogoodtime** [comment]
Hello, I'm a graduate student in the Department of Artificial Intelligence at
Sogang University. I registered and verified my account with my institutional
email (feelsogood@sogang.ac.kr), but login on download.php still fails.
Thank you very much!

@erkil1452

**Comment by Somnia1337** [comment]
Hi I ran into the same issue, I registered and logged in, but the link to download simply says "File is not allowed to download". Would you please grant me access to the dataset? Thanks!

@quantombone @adikhosla @andrewowens @visionATcsail

My email - [lujiange@stu.scu.edu.cn](mailto:lujiange@stu.scu.edu.cn)
