### ISSUE TITLE
training stuck problem

### ISSUE THREAD

**Issue by appleRtsan** [CSAILVision/GazeCapture#52]
Hi, thanks for sharing code and dataset.
I have some problem in training
I just run prepareDataset.py and then run the main.py
when running main.py, it stuck in the line 161:enumerate(train_loader)
when running that, the program runs out of my RAM by executing dozens of python and then the program get stucked, even not showing warning message, so I am sure that it is not memory error
My OS is windows and I use anaconda power shell, CUDA version is 10.1
How to fix that problem?

**Comment by erkil1452** [comment]
Try changing the number of worker (line 58 of main.py) threads to zero.

**Comment by appleRtsan** [comment]
Decreasing  amounts of thread really works for me, thanks!
