### ISSUE TITLE
Dataset is access denied

### ISSUE THREAD

**Issue by Jrebort** [CSAILVision/GazeCapture#53]
I am not to open the url` http://gazecapture.csail.mit.edu/download.php` to download the dataset.

**Comment by Jrebort** [comment]
I can access the url:`http://gazecapture.csail.mit.edu/download.php`
I want to reset my passwords, But you not to sent a email to support the reset of my password.
Can you help me?

**Comment by erkil1452** [comment]
If the issue is password (and not e.g. some IP block) then I can help you by resetting your entire account (you will have to register again). I need your e-mail address. Use our contact e-mail if you do not want to post it here.

**Comment by Jrebort** [comment]
I am send a e-mail to you yesterday, Please check your mailbox.Thanks @erkil1452

**Comment by Yoniming** [comment]
> I am send a e-mail to you yesterday, Please check your mailbox.Thanks @erkil1452
Hello, can you download this dataset now? I tried to register my email but couldn't log in. If possible, can I ask for your help to get the dataset？

**Comment by erkil1452** [comment]
Does the issue still persist? Note, that the accounts for gaze360 and gazecapture (itracker) are completely separate from each other.

**Comment by jyao22** [comment]
unable to register

**Comment by SaniyaSebastian** [comment]
Hey,I registered but got no response about the activation of the account.I was unable to login and download because of the activation issue
