### ISSUE TITLE
The dataset may not be downloaded due to registration problems

### ISSUE THREAD

**Issue by iszff** [CSAILVision/GazeCapture#59]
https://gazecapture.csail.mit.edu/download.php  
This site cannot be registered, but the data must be available after registration.😢

**Comment by erkil1452** [comment]
I am sorry. What is the issue?

**Comment by iszff** [comment]
<img width="1016" alt="register" src="https://user-images.githubusercontent.com/34810733/136235856-397b9097-daa4-4413-bbc1-e4d5c9cfb253.png">Unable to register with this registration popup

**Comment by erkil1452** [comment]
I just tested it. It seems that this situation may happen if a) the e-mail is already registered, b) the password is too short, c) the passwords do not match. Likely the latter since there is a red box around the password.
