### ISSUE TITLE
Inconsistency between described and actual model?

### ISSUE THREAD

**Issue by jakob1379** [CSAILVision/GazeCapture#6]
I am currently going through the pytorch eye model code and stumbled across an inconsistency that I suspect is being left out in the article on purpose, which just needs confirming. The described model does not mention max pooling but is being used between each layer in the code. 

The described model is as follows:
> The output is the distance, in centimeters, from the camera. CONV rep-
resents convolutional layers (with filter size/number of kernels: CONV-E1,CONV-F1: 11 × 11/96, CONV-E2,CONV-F2:
5 × 5/256, CONV-E3,CONV-F3: 3 × 3/384, CONV-E4,CONV-F4: 1 × 1/64)

but a max pool later can be seen between each layer in there code:
```
class ItrackerImageModel(nn.Module):
    # Used for both eyes (with shared weights) and the face (with unqiue weights)
    def __init__(self):
        super(ItrackerImageModel, self).__init__()
        self.features = nn.Sequential(
            nn.Conv2d(3, 96, kernel_size=11, stride=4, padding=0),
            nn.ReLU(inplace=True),
            nn.MaxPool2d(kernel_size=3, stride=2),
            nn.CrossMapLRN2d(size=5, alpha=0.0001, beta=0.75, k=1.0),
            nn.Conv2d(96, 256, kernel_size=5, stride=1, padding=2, groups=2),
            nn.ReLU(inplace=True),
            nn.MaxPool2d(kernel_size=3, stride=2),
            nn.CrossMapLRN2d(size=5, alpha=0.0001, beta=0.75, k=1.0),
            nn.Conv2d(256, 384, kernel_size=3, stride=1, padding=1),
            nn.ReLU(inplace=True),
            nn.Conv2d(384, 64, kernel_size=1, stride=1, padding=0),
            nn.ReLU(inplace=True),
       )
```
![2018-10-3010 59 19](https://user-images.githubusercontent.com/17257805/47710350-e0a22b80-dc32-11e8-8f6a-509ec7a37ec4.png)

**Comment by erkil1452** [comment]
Yes but the description also says "The exact model configuration is available on the project website." which refers to the caffe file https://github.com/CSAILVision/GazeCapture/blob/master/models/itracker_train_val.prototxt which is the reference implementation and should match this pytorch implementation.
