### ISSUE TITLE
Can't login to download a dataset 

### ISSUE THREAD

**Issue by dazzle-me** [CSAILVision/GazeCapture#60]
Hi! I'm a computer vision researcher from Moscow State University in Russia, I'm researching various of tasks including gaze estimation in the wild.
I registered and even received e-main confirmation about success of my registration (like, two month ago), but now after I tried to login, I failed, password restoration function doesn't work either 

Can you please take a look? I saw people reporting their e-mails in the thread, so I'll post mine, - 
*deleted since problem is resolved*

**Comment by erkil1452** [comment]
Hi. I see your account and it seems active. Perhaps you have forgotten your password. The password restoration service is not implemented unfortunately. I have deleted your account so you can now register again.
