### ISSUE TITLE
Webpage login problem

### ISSUE THREAD

**Issue by wonpyo-kim** [CSAILVision/GazeCapture#62]
Hello. 

I registered an accounts on gazecapture website yesterday. 
But I think I did screw up some questions...

My account is kwp@hallym.ac.kr, I think I didn't answer right answer on organization tab. 
My organization is Hallym University, please overwrite it or re-setup my account. 

Best regards.

**Comment by erkil1452** [comment]
Thank you for letting us know. Your record has been fixed. You should be able to log in.
