### ISSUE TITLE
access denied

### ISSUE THREAD

**Issue by AgentKu** [CSAILVision/GazeCapture#63]
I'm very sorry. Because I want to be able to log in and download the dataset as soon as possible. So I tried multiple times to log in. 
I have just registered and my account is agentku@i.smu.edu.cn. And I also received a letter from GazeCapture team with a verification link. It looks like I'm in a hurry. Hope you can help me.

**Comment by erkil1452** [comment]
Hi, I have just approved your application. You should be able to log in if you did not get already banned for too many attempts. If this is the case, I need to remove your IP from the banlist.

**Comment by AgentKu** [comment]
Thanks a lot , now I can log in
