### ISSUE TITLE
About data set download

### ISSUE THREAD

**Issue by a2296339232** [CSAILVision/GazeCapture#65]
Hello, I want to get the data set used in the project. I registered an account on the given website but could not log in. My email is 20202106022wsyu.edu.cn   I hope I can get help ,thank you

**Comment by erkil1452** [comment]
I am sorry but I cannot find such e-mail address (or even parts) in the DB. Did you receive a confirmation e-mail?

**Comment by a2296339232** [comment]
I think I need to confirm the registration procedure.
