### ISSUE TITLE
Problem with login and download

### ISSUE THREAD

**Issue by marycia624** [CSAILVision/GazeCapture#68]
Hello, I registered and confirmed email via link, but can't login and download dataset. I will grateful for your help. I try this emails:
265103@niuitmo.ru (confirmed)
265107@niuitmo.ru (can't confirm, the link don't work)

**Comment by joiellantero** [comment]
I have the same issue. Did you find a solution for this?

**Comment by erkil1452** [comment]
@marycia624 Both of those e-mails have been fully approved for a while. Is it possible you have reached your failed login attempt limit? That would block your IP. Or perhaps you have forgotten your password? I can also reset that.

**Comment by erkil1452** [comment]
@joiellantero I can also look into your account but I do not know your e-mail. You can send us e-mail if you do not want to share it here.

**Comment by joiellantero** [comment]
@erkil1452 Thanks, the email I used for my account is joie.llantero@eee.upd.edu.ph

**Comment by erkil1452** [comment]
Ok, you can now register again and I will approve it.

**Comment by erkil1452** [comment]
Ok, you should now be able to log in.

**Comment by joiellantero** [comment]
Thank you! I'm able to access the dataset now.
