### ISSUE TITLE
Confused about the how to take the model output to angular error.

### ISSUE THREAD

**Issue by qub-arise** [CSAILVision/GazeCapture#73]
Hi there, 

I am a little confused about how to compute the GazeCapture gaze labels (x, y) as angle, I have searched through the paper but couldn't find one. I do know for example [here](https://github.com/ishtos/mpII-face-gaze/blob/1215ef0e08f214ef65e44bfd14baaa587dadeefe/main.py#L58) that one is able to compute the angular error. However, they are able to do so cos the gaze labels are gaze vectors.
Can you kindly help? Many thanks.

**Comment by erkil1452** [comment]
Hi, this is a 2D model and it predicts gaze fixations on a 2D screen of the device. If you want to convert this to 3D vectors (to compute angular errors), you need to know exact pose of your device (or at least its distance). You can probably do some estimation from the head size in the image but it will not be very accurate. In practice, if you want to work with angles, you should use a dataset labeled with 3D labels.
